/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: f86ff95c70da6795a1acc235ee9b9eed)
interface __BaseEnv_Env {
	METTI_MCP_UPSTREAM_URL: string;
	SUPABASE_AUTH_SERVER_URL: string;
	MCP_ALLOWED_ORIGINS: string;
	MCP_ALLOWED_HOSTS: string;
	MCP_MAX_BODY_BYTES: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "METTI_MCP_UPSTREAM_URL" | "SUPABASE_AUTH_SERVER_URL" | "MCP_ALLOWED_ORIGINS" | "MCP_ALLOWED_HOSTS" | "MCP_MAX_BODY_BYTES">> {}
}
